/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 cyberpunk_room.glb
Author: Phons (https://sketchfab.com/Phons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-room-cubicle-0740c506707e4678a96dc6b705037574
Title: Cyberpunk Room Cubicle
*/

import React, { useState } from "react";
import { useGLTF, Html } from "@react-three/drei";
import "../styles/Models.css";

const CyberpunkRoom = (props) => {
  const { nodes, materials } = useGLTF("models/cyberpunk_room.glb");
  const [lightsOn, setLightsOn] = useState(false);

  const toggleLights = () => {
    setLightsOn(!lightsOn);
  };

  return (
    <>
      <Html className="text">
        <button onClick={toggleLights} className="action-button">
          {lightsOn ? "Lights off" : "Lights on"}
        </button>
      </Html>
      <group {...props} dispose={null}>
        <group position={[1.198, -0.124, -0.827]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Material}
          />
          {lightsOn && (
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.Yeet}
            />
          )}
        </group>
      </group>
    </>
  );
};

useGLTF.preload("models/cyberpunk_room.glb");
export default CyberpunkRoom;
