/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 kitchen.glb 
Author: Ekaterina Riazanova (https://sketchfab.com/themechanicthe)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/evening-routine-f657483a227b4571951ccb45a5a3312e
Title: Evening Routine
*/

import React, { useState, useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Kitchen = (props) => {
  const { nodes, materials } = useGLTF("models/kitchen.glb");
  const [seat, takeSeat] = useState(false);

  const Movechair = () => {
    takeSeat(!seat);
  };

  // Clock

  const [clockHandsRotation, setClockHandsRotation] = useState(0);
  const clockHandsRef = useRef();

  useFrame(() => {
    setClockHandsRotation((prevRotation) => prevRotation + 0.005);
    clockHandsRef.current.rotation.y = clockHandsRotation;
  });

  return (
    <group {...props} dispose={null}>
      <Html className="text">
        <button onClick={Movechair} className="action-button">
          {seat ? "Stand up" : "Have a seat"}
        </button>
      </Html>

      {/* Chair left */}

      <group position={seat ? [4.9, 1.524, -0.684] : [4.062, 1.524, -0.684]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.black_plactic_stove}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.metal_black_stove}
          position={[-0.138, -0.907, -0.493]}
          rotation={[-Math.PI, 1.298, -Math.PI]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.metal_black_stove}
          position={[-0.493, -0.907, 0.138]}
          rotation={[-Math.PI, -0.273, -Math.PI]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.metal_black_stove}
          position={[0.138, -0.907, 0.493]}
          rotation={[0, -1.298, 0]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.metal_black_stove}
          position={[0.493, -0.907, -0.138]}
          rotation={[0, 0.273, 0]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.metal_black_stove}
          position={[0, -0.943, 0]}
          rotation={[0, 0.273, 0]}
        />
      </group>

      <group position={[4.062, 1.524, -2.856]} rotation={[0, 0.698, 0]}>
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.black_plactic_stove}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.metal_black_stove}
          position={[0.493, -0.907, -0.138]}
          rotation={[0, 0.273, 0]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.metal_black_stove}
          position={[-0.138, -0.907, -0.493]}
          rotation={[-Math.PI, 1.298, -Math.PI]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.metal_black_stove}
          position={[-0.493, -0.907, 0.138]}
          rotation={[-Math.PI, -0.273, -Math.PI]}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.metal_black_stove}
          position={[0.138, -0.907, 0.493]}
          rotation={[0, -1.298, 0]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.metal_black_stove}
          position={[0, -0.943, 0]}
          rotation={[0, 0.273, 0]}
        />
      </group>

      {/* blinds */}
      <group position={[0.512, 6.897, -4.441]}>
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials["blinds.001"]}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.blinds}
          position={[0, -0.081, -0.008]}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.blinds}
          position={[-0.596, -1.688, -0.008]}
          rotation={[0.117, 0, 0]}
          scale={[1.037, 0.014, 0.073]}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.blinds}
          position={[0, -1.727, -0.008]}
          scale={[1.037, 0.014, 0.073]}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.blinds}
          position={[0.108, -0.83, -0.036]}
          scale={[0.012, 0.859, 0.012]}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.blinds}
          position={[0.108, -0.83, 0.026]}
          scale={[0.012, 0.859, 0.012]}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.blinds}
          position={[0.852, -0.475, 0.087]}
          scale={[0.008, 0.494, 0.008]}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.blinds}
          position={[-0.856, -0.6, 0.087]}
          scale={[0.012, 0.494, 0.012]}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.blinds}
          position={[0.852, -0.964, 0.087]}
          scale={[0.037, 0.076, 0.037]}
        />
      </group>
      <group position={[0.512, 5.717, -4.729]}>
        <group
          position={[-0.596, 0, 0]}
          rotation={[-Math.PI, 0, Math.PI]}
          scale={[-0.828, 0.828, 1.741]}
        >
          <mesh
            geometry={nodes.Object_49.geometry}
            material={materials.wood_window_vertical}
          />
          <mesh
            geometry={nodes.Object_50.geometry}
            material={materials.wood_window_horizontal}
          />
        </group>
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.wood_window_vertical}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.wood_window_horizontal}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials.glass_cabinets}
          position={[-0.592, -1.256, 0.142]}
        />
      </group>
      <group position={[-3.356, 3.04, -3.256]} rotation={[0, -0.461, 0]}>
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials.toster_main}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.toster_down}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.metal_toster}
          position={[0.319, 0.277, 0.461]}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.metal_toster}
          position={[0.406, 0.304, 0.542]}
        />
        <mesh
          geometry={nodes.Object_61.geometry}
          material={materials.metal_toster}
          position={[0, -0.215, 0]}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.toster_down}
          position={[0.256, -0.539, 0.409]}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.metal_toster}
          position={[0.084, -0.136, 0.643]}
          rotation={[0, 0.039, 0]}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.metal_toster}
          position={[0, -0.136, 0.656]}
        />
        <mesh
          geometry={nodes.Object_69.geometry}
          material={materials.metal_toster}
          position={[0, -0.35, 0]}
        />
      </group>
      <group position={[-3.251, 2.876, -1.134]}>
        <mesh
          geometry={nodes.Object_71.geometry}
          material={materials.pink_gradient_pot_up}
        />
        <mesh
          geometry={nodes.Object_73.geometry}
          material={materials.pink_gradient_pot_hand}
          position={[0, 0.396, 0.67]}
          scale={1.376}
        />

        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.pink_gradient_pot_up}
          position={[0.657, 0.456, -0.005]}
        />
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials.metal_white_pot}
          position={[0, 0.696, 0.017]}
          scale={[0.128, 0.145, 0.128]}
        />
      </group>
      <group position={[-3.222, 2.659, -0.37]}>
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials.metal_black_stove}
        />
        <mesh
          geometry={nodes.Object_81.geometry}
          material={materials.teflon_black_stove}
          position={[-0.042, 0.173, -0.764]}
        />
        <mesh
          geometry={nodes.Object_83.geometry}
          material={materials.metal_white_hood}
          position={[-0.034, 0.113, -0.757]}
        />
        <mesh
          geometry={nodes.Object_85.geometry}
          material={materials.black_plactic_stove}
          position={[0.859, -0.015, -0.757]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.06, 0.017, 0.06]}
        />
        <mesh
          geometry={nodes.Object_87.geometry}
          material={materials.black_plactic_stove}
          position={[0.876, -0.015, -0.757]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.047, 0.014, 0.047]}
        />
        <mesh
          geometry={nodes.Object_89.geometry}
          material={materials.red_stove}
          position={[0.853, -0.015, -0.28]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.037, 0.023, 0.037]}
        />
        <mesh
          geometry={nodes.Object_91.geometry}
          material={materials.metal_black_stove}
          position={[0.682, -0.087, -1.291]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.074, 0.033, 0.074]}
        />
      </group>
      <group position={[-3.442, 3.491, -3.301]} rotation={[0, -0.461, 0]}>
        <mesh
          geometry={nodes.Object_93.geometry}
          material={materials.bread_out}
        />
        <mesh
          geometry={nodes.Object_94.geometry}
          material={materials.bread_in}
        />
      </group>
      <group position={[-0.176, 2.337, -1.199]}>
        <mesh geometry={nodes.Object_96.geometry} material={materials.marble} />
        <mesh
          geometry={nodes.Object_98.geometry}
          material={materials.wood_boxes_1}
          position={[-1.923, -1.264, -0.689]}
        />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.wood_boxes_1}
          position={[-1.945, -2.086, 0.853]}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.wood_boxes_1}
          position={[-1.923, -0.312, -0.689]}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.wood_boxes_1}
          position={[0.02, -1.264, -1.312]}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.wood_boxes_1}
          position={[-1.923, -1.264, 2.53]}
        />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials.wood_boxes_1}
          position={[-1.271, -1.264, -1.312]}
        />
        <mesh
          geometry={nodes.Object_110.geometry}
          material={materials.wood_boxes_1}
          position={[1.393, -1.264, -1.342]}
        />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={materials.wood_boxes_2}
          position={[-1.099, -1.324, -0.002]}
        />
        <mesh
          geometry={nodes.Object_114.geometry}
          material={materials.table_legs}
          position={[4.137, -1.303, 1.754]}
        />
        <mesh
          geometry={nodes.Object_116.geometry}
          material={materials.gold}
          position={[-1.813, -2.086, 0.853]}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_118.geometry}
          material={materials.gold}
          position={[0.879, -0.704, -1.206]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Object_120.geometry}
          material={materials.gold}
          position={[-1.813, -0.32, -0.689]}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_122.geometry}
          material={materials.gold}
          position={[0.489, -0.704, -1.206]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Object_124.geometry}
          material={materials.gold}
          position={[-1.825, -0.702, 2.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_126.geometry}
          material={materials.gold}
          position={[-1.813, -1.171, -0.689]}
          rotation={[-Math.PI, 0, 0]}
        />
      </group>
      <group
        position={[-4.475, 7.162, 3.394]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 0.104, 1]}
      >
        <mesh
          geometry={nodes.Object_128.geometry}
          material={materials.yellow_clock}
        />
        <mesh
          geometry={nodes.Object_130.geometry}
          material={materials.clock_black}
          position={[-0.796, 1.003, 0]}
          scale={[1, 9.625, 1]}
        />
        <mesh
          geometry={nodes.Object_132.geometry}
          material={materials.clock_black}
          position={[0, 1.003, 0.796]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 9.625, 1]}
        />
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.clock_black}
          position={[-0.398, 1.003, 0.689]}
          rotation={[0, Math.PI / 3, 0]}
          scale={[1, 9.625, 1]}
        />
        {/* minute hand */}
        <mesh
          ref={clockHandsRef}
          geometry={nodes.Object_136.geometry}
          material={materials.clock_black}
          position={[0, 1.207, 0]}
          scale={[1, 9.625, 1]}
        />
        {/* Hour hand */}
        <mesh
          geometry={nodes.Object_138.geometry}
          material={materials.clock_black}
          position={[0, 1.562, 0]}
          rotation={[0, Math.PI / 6, 0]}
          scale={[1, 9.625, 1]}
        />
        <mesh
          geometry={nodes.Object_140.geometry}
          material={materials.clock_black}
          position={[-0.689, 1.003, 0.398]}
          rotation={[0, Math.PI / 6, 0]}
          scale={[1, 9.625, 1]}
        />
      </group>
      <group
        position={[3.09, 2.51, -0.224]}
        rotation={[0.38, 0, 0]}
        scale={[0.084, 0.072, 0.084]}
      >
        <mesh
          geometry={nodes.Object_144.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_146.geometry}
          material={materials["Material.001"]}
          position={[-0.194, 0.411, 0]}
        />
      </group>
      <group
        position={[2.905, 2.5, -0.198]}
        rotation={[1.878, 1.171, -1.903]}
        scale={[0.084, 0.072, 0.084]}
      >
        <mesh
          geometry={nodes.Object_148.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_150.geometry}
          material={materials["Material.001"]}
          position={[-0.194, 0.411, 0]}
        />
      </group>
      <group
        position={[3.191, 2.51, -2.299]}
        rotation={[0.884, -1.07, 0.819]}
        scale={[0.084, 0.072, 0.084]}
      >
        <mesh
          geometry={nodes.Object_152.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_154.geometry}
          material={materials["Material.001"]}
          position={[-0.194, 0.411, 0]}
        />
      </group>
      <group
        position={[2.956, 2.5, -2.272]}
        rotation={[0.389, 0.209, -0.085]}
        scale={[0.084, 0.072, 0.084]}
      >
        <mesh
          geometry={nodes.Object_156.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_158.geometry}
          material={materials["Material.001"]}
          position={[-0.194, 0.411, 0]}
        />
      </group>
      <group position={[0.036, 2.38, -3.41]}>
        <mesh
          geometry={nodes.Object_166.geometry}
          material={materials.ceramic_sink}
        />
        <mesh
          geometry={nodes.Object_168.geometry}
          material={materials.ceramic_sink}
          position={[0, 0.97, -0.332]}
        />
        <mesh
          geometry={nodes.Object_170.geometry}
          material={materials.ceramic_sink}
          position={[-0.002, 0.35, -0.682]}
        />
        <mesh
          geometry={nodes.Object_172.geometry}
          material={materials.ceramic_sink}
          position={[0.218, 0.436, -0.682]}
        />
        <mesh
          geometry={nodes.Object_174.geometry}
          material={materials.ceramic_sink}
          position={[0.288, 0.514, -0.682]}
        />
      </group>
      <group position={[-3.383, 2.643, 3.307]}>
        <mesh
          geometry={nodes.Object_176.geometry}
          material={materials.freezer}
        />
        <mesh
          geometry={nodes.Object_178.geometry}
          material={materials.freezer}
          position={[1.743, -0.236, 0.001]}
          rotation={[-Math.PI, 0, 0]}
          scale={[1.635, 1, 1]}
        />
        <mesh
          geometry={nodes.Object_180.geometry}
          material={materials.freezer}
          position={[1.743, 1.927, 0.001]}
          scale={[1.635, 1, 1]}
        />
        <mesh
          geometry={nodes.Object_182.geometry}
          material={materials.metal}
          position={[2.056, 1.058, -0.473]}
        />
        <mesh
          geometry={nodes.Object_184.geometry}
          material={materials.material_0}
          position={[1.455, 2.696, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_186.geometry}
          material={materials.material_0}
          position={[1.491, 2.68, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_188.geometry}
          material={materials.material_0}
          position={[1.455, 0.952, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_190.geometry}
          material={materials.material_0}
          position={[1.491, 0.936, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_192.geometry}
          material={materials.material_0}
          position={[1.455, 0.763, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_194.geometry}
          material={materials.material_0}
          position={[1.491, 0.747, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_196.geometry}
          material={materials.material_0}
          position={[1.455, -2.132, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_198.geometry}
          material={materials.material_0}
          position={[1.491, -2.148, 1.158]}
          scale={[0.023, 0.008, 0.009]}
        />
        <mesh
          geometry={nodes.Object_200.geometry}
          material={materials.metal}
          position={[2.002, 2.017, 0.013]}
          scale={[1.088, 1.012, 1.012]}
        />
        <mesh
          geometry={nodes.Object_202.geometry}
          material={materials.metal}
          position={[2.008, 2.017, 0.013]}
        />
      </group>
      <group position={[-2.115, 1.122, -0.345]}>
        <mesh
          geometry={nodes.Object_204.geometry}
          material={materials.metal_oven}
        />
        <mesh
          geometry={nodes.Object_206.geometry}
          material={materials["bread.002"]}
          position={[-1.461, -0.075, -0.536]}
        />
        <mesh
          geometry={nodes.Object_208.geometry}
          material={materials["bread.002"]}
          position={[-0.68, -0.075, -0.536]}
        />
        <mesh
          geometry={nodes.Object_210.geometry}
          material={materials.plastic}
          position={[0.103, 0.412, 0.001]}
          scale={[0.027, 0.044, 0.449]}
        />
        <mesh
          geometry={nodes.Object_212.geometry}
          material={materials.metal_black_stove}
          position={[-1.059, -0.098, 0.122]}
          scale={[1, 0.044, 1]}
        />
        <mesh
          geometry={nodes.Object_214.geometry}
          material={materials.metal_oven}
          position={[-0.045, 0, 0]}
          scale={[0.046, 0.82, 0.957]}
        />
        <mesh
          geometry={nodes.Object_216.geometry}
          material={materials.metal_oven_2}
          position={[0.003, 0.807, 0]}
        />
        <mesh
          geometry={nodes.Object_218.geometry}
          material={materials.plastic}
          position={[0.069, 0.795, 0.425]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.09, 0.031, 0.09]}
        />
        <mesh
          geometry={nodes.Object_220.geometry}
          material={materials.plastic}
          position={[0.11, 0.795, 0.425]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.061, 0.013, 0.061]}
        />
        <mesh
          geometry={nodes.Object_222.geometry}
          material={materials["ceramic.001"]}
          position={[0.029, 0, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.341, 0.739, 0.739]}
        />
      </group>
      <group position={[-3.687, 4.832, -0.37]} scale={[0.855, 0.102, 1.483]}>
        <mesh
          geometry={nodes.Object_226.geometry}
          material={materials.metal_white_hood}
        />
        <mesh
          geometry={nodes.Object_228.geometry}
          material={materials.metal_white_hood}
          position={[0.002, -2.986, 0]}
          scale={[0.881, 1, 0.91]}
        />
        <mesh
          geometry={nodes.Object_230.geometry}
          material={materials.metal_black_stove}
          position={[1.002, -0.056, -0.034]}
          scale={[0.022, 0.676, 0.389]}
        />
      </group>
      <group position={[-3.879, 8.399, -1.292]} scale={[0.7, 0.102, 3.186]}>
        <mesh
          geometry={nodes.Object_232.geometry}
          material={materials.wood_boxes_2}
        />
        <mesh
          geometry={nodes.Object_234.geometry}
          material={materials.wood_boxes_2}
          position={[0, -21.996, 0]}
        />
        <mesh
          geometry={nodes.Object_236.geometry}
          material={materials.wood_boxes_1}
          position={[1.115, -11.025, 0.714]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_238.geometry}
          material={materials.wood_boxes_2}
          position={[0.003, -10.974, 1.03]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_240.geometry}
          material={materials.wood_boxes_2}
          position={[0, -10.998, -0.965]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.032, 11.961]}
        />
        <mesh
          geometry={nodes.Object_242.geometry}
          material={materials.wood_boxes_1}
          position={[1.073, -11.025, 0.795]}
          scale={[0.036, 8.226, 0.016]}
        />
        <mesh
          geometry={nodes.Object_244.geometry}
          material={materials.wood_boxes_1}
          position={[1.087, -11.025, 0.142]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_246.geometry}
          material={materials.wood_boxes_2}
          position={[0, -10.998, -0.545]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.939, 0.032, 10.575]}
        />
        <mesh
          geometry={nodes.Object_248.geometry}
          material={materials.wood_boxes_2}
          position={[0, -10.998, -0.092]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.939, 0.032, 10.575]}
        />
        <mesh
          geometry={nodes.Object_250.geometry}
          material={materials.wood_boxes_2}
          position={[0, -10.998, 0.365]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.939, 0.032, 10.575]}
        />
        <mesh
          geometry={nodes.Object_252.geometry}
          material={materials.wood_boxes_1}
          position={[1.073, -6.387, 0.712]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.033, 0.263, 0.511]}
        />
        <mesh
          geometry={nodes.Object_254.geometry}
          material={materials.gold}
          position={[1.287, -20.545, 0.714]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_256.geometry}
          material={materials.gold}
          position={[1.287, -20.545, 0.142]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_258.geometry}
          material={materials.gold}
          position={[1.287, -20.545, -0.312]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_260.geometry}
          material={materials.gold}
          position={[1.287, -20.545, -0.767]}
          scale={[1.429, 9.823, 0.314]}
        />
        <mesh
          geometry={nodes.Object_262.geometry}
          material={materials.glass_cabinets}
          position={[1.166, -19.507, 0.711]}
          scale={[1.429, 9.823, 0.314]}
        />
      </group>
      <group position={[-2.242, 2.578, -3.208]} scale={0.916}>
        <mesh
          geometry={nodes.Object_264.geometry}
          material={materials.lemon_main}
        />
        <mesh
          geometry={nodes.Object_265.geometry}
          material={materials.lemon_white}
        />
        <mesh
          geometry={nodes.Object_266.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-1.983, 2.578, -3.029]} scale={[0.752, 0.867, 0.752]}>
        <mesh
          geometry={nodes.Object_268.geometry}
          material={materials.lemon_main}
        />
        <mesh
          geometry={nodes.Object_269.geometry}
          material={materials.lemon_white}
        />
        <mesh
          geometry={nodes.Object_270.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.114, 2.6, -3.299]}
        rotation={[-0.013, 0.557, -0.138]}
        scale={[0.806, 0.916, 0.806]}
      >
        <mesh
          geometry={nodes.Object_272.geometry}
          material={materials.lemon_main}
        />
        <mesh
          geometry={nodes.Object_273.geometry}
          material={materials.lemon_white}
        />
        <mesh
          geometry={nodes.Object_274.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-1.931, 2.6, -3.329]}
        rotation={[-0.013, 0.557, -0.184]}
        scale={[0.806, 0.916, 0.806]}
      >
        <mesh
          geometry={nodes.Object_276.geometry}
          material={materials.lemon_main}
        />
        <mesh
          geometry={nodes.Object_277.geometry}
          material={materials.lemon_white}
        />
        <mesh
          geometry={nodes.Object_278.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-1.914, 2.606, -3.071]} scale={[0.457, 0.626, 0.457]}>
        <mesh
          geometry={nodes.Object_280.geometry}
          material={materials.lemon_main}
        />
        <mesh
          geometry={nodes.Object_281.geometry}
          material={materials.lemon_white}
        />
        <mesh
          geometry={nodes.Object_282.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-2.632, 6.078, 3.807]} scale={0.349}>
        <mesh
          geometry={nodes.Object_300.geometry}
          material={materials.ceramic_sink}
        />
        <mesh
          geometry={nodes.Object_301.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Object_303.geometry}
          material={materials.green}
          position={[-1.182, -4.425, 2.343]}
          rotation={[0.703, -0.995, -0.285]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_305.geometry}
          material={materials.green}
          position={[-0.824, -3.999, 2.676]}
          rotation={[0.319, -0.24, 0.112]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_307.geometry}
          material={materials.green}
          position={[-0.99, -3.624, 2.46]}
          rotation={[1.188, -1.345, 0.665]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_309.geometry}
          material={materials.green}
          position={[-1.109, -3.176, 2.522]}
          rotation={[-1.001, -0.838, -1.455]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_311.geometry}
          material={materials.green}
          position={[-0.778, -7.462, 2.438]}
          rotation={[0.78, -0.786, -0.338]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_313.geometry}
          material={materials.green}
          position={[-0.345, -7.098, 2.635]}
          rotation={[0.451, 0.261, 0.044]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_315.geometry}
          material={materials.green}
          position={[-0.641, -6.624, 2.748]}
          rotation={[-2.165, 0.329, 2.165]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_317.geometry}
          material={materials.green}
          position={[-0.621, -3.033, 2.841]}
          rotation={[-0.077, -0.216, -0.369]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_319.geometry}
          material={materials.green}
          position={[-0.84, -2.642, 2.354]}
          rotation={[1.45, -1.29, 1.09]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_321.geometry}
          material={materials.green}
          position={[-0.225, -1.663, 2.515]}
          rotation={[-0.06, 0.399, 0.604]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_323.geometry}
          material={materials.green}
          position={[-0.413, -2.457, 2.596]}
          rotation={[0.462, -0.107, 0.318]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_325.geometry}
          material={materials.green}
          position={[-0.612, -2.082, 2.526]}
          rotation={[0.507, -0.215, -0.259]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_327.geometry}
          material={materials.green}
          position={[-0.742, -1.526, 2.08]}
          rotation={[0.39, -1.49, -0.032]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_329.geometry}
          material={materials.green}
          position={[-0.355, -1.353, 2.41]}
          rotation={[-0.15, 0.12, -0.081]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_331.geometry}
          material={materials.green}
          position={[-0.739, -1.094, 2.084]}
          rotation={[-0.497, -0.884, -0.424]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_333.geometry}
          material={materials.green}
          position={[-0.372, 0.782, 1.198]}
          rotation={[-1.536, -0.653, -1.767]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_335.geometry}
          material={materials.green}
          position={[-0.726, -6.212, 2.506]}
          rotation={[0.199, -1.151, -0.206]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_337.geometry}
          material={materials.green}
          position={[-0.387, -6.487, 2.772]}
          rotation={[0.635, 0.481, -1.345]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_339.geometry}
          material={materials.green}
          position={[-0.2, -5.858, 2.667]}
          rotation={[0.461, 0.159, 0.149]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_341.geometry}
          material={materials.green}
          position={[-0.47, -5.223, 2.684]}
          rotation={[-0.359, -0.454, -1.6]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_343.geometry}
          material={materials.green}
          position={[-0.212, -4.884, 2.799]}
          rotation={[-0.081, 0.117, -0.853]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_345.geometry}
          material={materials.green}
          position={[-0.435, -4.414, 2.716]}
          rotation={[-0.081, -0.681, -0.554]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_347.geometry}
          material={materials.green}
          position={[0.128, -4.312, 2.485]}
          rotation={[3.141, 1.083, 1.602]}
          scale={0.463}
        />
        <mesh
          geometry={nodes.Object_349.geometry}
          material={materials.green}
          position={[-0.136, -3.966, 2.754]}
          rotation={[0.239, 0.488, -0.465]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_351.geometry}
          material={materials.green}
          position={[-0.485, -3.388, 2.595]}
          rotation={[0.695, -0.136, -0.43]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_353.geometry}
          material={materials.green}
          position={[-0.157, -3.217, 2.56]}
          rotation={[0.754, 0.641, -0.019]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_355.geometry}
          material={materials.green}
          position={[-0.114, -2.853, 2.622]}
          rotation={[-0.483, 0.614, 0.582]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_357.geometry}
          material={materials.green}
          position={[-0.042, -2.48, 2.393]}
          rotation={[-0.074, 1.239, 0.547]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_359.geometry}
          material={materials.green}
          position={[0.286, -0.732, 1.603]}
          rotation={[1.379, -1.031, 0.84]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_361.geometry}
          material={materials.green}
          position={[-0.186, -0.755, 1.8]}
          rotation={[0.189, 0.048, 0.34]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_363.geometry}
          material={materials.green}
          position={[-0.616, -0.233, 1.443]}
          rotation={[0.266, -0.939, -0.97]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_365.geometry}
          material={materials.green}
          position={[-0.151, 0.035, 1.477]}
          rotation={[0.854, -0.043, 0.077]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_367.geometry}
          material={materials.green}
          position={[-0.198, 0.482, 0.835]}
          rotation={[-2.916, -0.68, 3.004]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_369.geometry}
          material={materials.green}
          position={[0.522, 0.709, 1.268]}
          rotation={[-1.444, 0.786, 1.794]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_371.geometry}
          material={materials.green}
          position={[-0.274, 0.413, -0.111]}
          rotation={[-2.604, -0.421, -2.563]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_373.geometry}
          material={materials.green}
          position={[0.559, -6.862, 2.801]}
          rotation={[-2.229, -0.733, 2.528]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_375.geometry}
          material={materials.green}
          position={[0.587, -6.166, 2.627]}
          rotation={[1.723, -0.851, -0.106]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_377.geometry}
          material={materials.green}
          position={[0.265, -6.143, 2.808]}
          rotation={[-0.333, 0.091, 0.009]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_379.geometry}
          material={materials.green}
          position={[0.472, -5.666, 2.382]}
          rotation={[-0.06, 1.254, 1.152]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_381.geometry}
          material={materials.green}
          position={[0.41, -4.928, 2.327]}
          rotation={[-0.713, 0.967, 2.241]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_383.geometry}
          material={materials.green}
          position={[0.491, 0.07, 1.897]}
          rotation={[-0.426, 0.197, 0.223]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_385.geometry}
          material={materials.green}
          position={[-0.397, 0.368, 1.283]}
          rotation={[0.353, -1.317, -0.412]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_387.geometry}
          material={materials.green}
          position={[0.527, 0.316, 1.627]}
          rotation={[-0.082, 0.905, -0.092]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_389.geometry}
          material={materials.green}
          position={[0.379, 0.563, 0.339]}
          rotation={[-1.958, 0.693, 1.899]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_391.geometry}
          material={materials.green}
          position={[0.3, -7.761, 2.365]}
          rotation={[1.218, -1.047, 0.495]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_393.geometry}
          material={materials.green}
          position={[0.512, -8.254, 2.568]}
          rotation={[0.584, -0.173, -0.128]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_395.geometry}
          material={materials.green}
          position={[0.707, -7.192, 2.44]}
          rotation={[0.151, 1.422, -0.022]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_397.geometry}
          material={materials.green}
          position={[0.667, -4.434, 2.431]}
          rotation={[1.027, 0.346, 0.659]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_399.geometry}
          material={materials.green}
          position={[0.639, -3.997, 2.294]}
          rotation={[1.518, 0.899, -0.543]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_401.geometry}
          material={materials.green}
          position={[0.408, -3.677, 2.55]}
          rotation={[0.84, -0.086, -0.235]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_403.geometry}
          material={materials.green}
          position={[0.245, -3.1, 2.299]}
          rotation={[1.308, -1.149, 0.794]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_405.geometry}
          material={materials.green}
          position={[0.867, -3.136, 2.427]}
          rotation={[0.128, 1.079, 0.921]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_407.geometry}
          material={materials.green}
          position={[0.657, -2.294, 2.43]}
          rotation={[0.779, -0.707, 0.55]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_409.geometry}
          material={materials.green}
          position={[0.729, -2.61, 2.467]}
          rotation={[0.518, 0.732, -0.525]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_411.geometry}
          material={materials.green}
          position={[0.931, -0.858, 2.198]}
          rotation={[-0.773, 0.939, -0.145]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_413.geometry}
          material={materials.green}
          position={[0.675, -0.412, 1.964]}
          rotation={[-0.19, 0.723, -0.029]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_415.geometry}
          material={materials.green}
          position={[0.225, 0.424, 0.908]}
          rotation={[-2.939, 1.029, 2.96]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_417.geometry}
          material={materials.green}
          position={[0.785, 0.509, -0.023]}
          rotation={[-2.287, -1.029, -2.532]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_419.geometry}
          material={materials.green}
          position={[0.246, 0.279, -0.516]}
          rotation={[-2.789, 0.027, 3.064]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_421.geometry}
          material={materials.green}
          position={[1.137, -1.358, 1.992]}
          rotation={[0.333, 1.062, 0.548]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_423.geometry}
          material={materials.green}
          position={[0.399, -1.136, 1.879]}
          rotation={[0.649, -0.822, -0.108]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_425.geometry}
          material={materials.green}
          position={[0.949, 0.484, -0.39]}
          rotation={[-2.443, -0.809, -2.528]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_427.geometry}
          material={materials.green}
          position={[1.577, 0.271, -0.374]}
          rotation={[3.074, 0.788, 2.993]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_429.geometry}
          material={materials.green}
          position={[1.137, -2.531, 2.476]}
          rotation={[0.67, 0.548, -0.866]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_431.geometry}
          material={materials.green}
          position={[1.061, -2.061, 2.495]}
          rotation={[0.061, 0.272, -0.142]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_433.geometry}
          material={materials.green}
          position={[1.25, 0.42, 0.548]}
          rotation={[-0.068, 0.155, -0.237]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_435.geometry}
          material={materials.green}
          position={[1.656, 0.002, -0.066]}
          rotation={[0.276, 0.657, -0.249]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_437.geometry}
          material={materials.green}
          position={[0.528, -1.803, 2.323]}
          rotation={[0.119, -0.561, -0.366]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_439.geometry}
          material={materials.green}
          position={[1.48, -1.156, 1.051]}
          rotation={[0.248, 0.282, -0.343]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_441.geometry}
          material={materials.green}
          position={[1.853, -0.835, 0.773]}
          rotation={[0.134, 1.499, -0.529]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_443.geometry}
          material={materials.green}
          position={[1.677, -0.216, 0.837]}
          rotation={[0.414, 0.59, -0.771]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_445.geometry}
          material={materials.green}
          position={[1.769, 0.18, 0.438]}
          rotation={[0.187, 1.432, -0.402]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_447.geometry}
          material={materials.green}
          position={[1.512, -0.998, -0.266]}
          rotation={[1.081, 0.821, -1.131]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_449.geometry}
          material={materials.green}
          position={[1.717, -0.516, -0.425]}
          rotation={[2.273, 1.229, -2.089]}
          scale={0.562}
        />
        <mesh
          geometry={nodes.Object_451.geometry}
          material={materials["Material.006"]}
          position={[0.417, -1.659, 1.263]}
          scale={2.869}
        />
      </group>
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.ceramic_glass_plate}
        position={[3.04, 2.504, -0.456]}
        scale={[0.563, 0.053, 0.563]}
      />
      <mesh
        geometry={nodes.Object_160.geometry}
        material={materials.ceramic_glass}
        position={[2.463, 2.777, -1.078]}
        scale={[0.191, 0.324, 0.191]}
      />
      <mesh
        geometry={nodes.Object_162.geometry}
        material={materials.wood_for_glass}
        position={[2.461, 2.496, -1.077]}
      />
      <mesh
        geometry={nodes.Object_164.geometry}
        material={materials.wood_fork}
        position={[3.231, 2.48, -1.192]}
      />
      <mesh
        geometry={nodes.Object_224.geometry}
        material={materials["Material.005"]}
        position={[-2.186, 2.517, -3.398]}
        scale={0.778}
      />
      <mesh
        geometry={nodes.Object_284.geometry}
        material={materials.ceramic}
        position={[-4.595, 8.871, 5.369]}
        scale={[0.047, 0.27, 0.27]}
      />
      <mesh
        geometry={nodes.Object_286.geometry}
        material={materials.wood_floor}
        position={[5.201, -0.22, 4.831]}
      />
      <mesh
        geometry={nodes.Object_288.geometry}
        material={materials.wood_floor}
        position={[4.72, -0.22, 4.103]}
      />
      <mesh
        geometry={nodes.Object_290.geometry}
        material={materials.wood_floor}
        position={[4.72, -0.22, 5.144]}
      />
      <mesh
        geometry={nodes.Object_292.geometry}
        material={materials.wood_floor}
        position={[5.203, -0.22, -4.305]}
      />
      <mesh
        geometry={nodes.Object_294.geometry}
        material={materials.main_wood}
        position={[0.284, -0.48, 0.362]}
      />
      <mesh
        geometry={nodes.Object_296.geometry}
        material={materials.wall_main}
        position={[-4.637, 4.459, 0]}
        scale={[0.059, 4.711, 4.658]}
      />
      <mesh
        geometry={nodes.Object_298.geometry}
        material={materials.wall_main}
        position={[-0.206, 4.436, -4.578]}
      />
      <mesh
        geometry={nodes.Object_453.geometry}
        material={materials.ceramic_glass_plate}
        position={[3.04, 2.504, -2.531]}
        scale={[0.563, 0.053, 0.563]}
      />
      <mesh
        geometry={nodes.Object_455.geometry}
        material={materials.ceramic_glass}
        position={[2.464, 2.777, -3.236]}
        scale={[0.191, 0.324, 0.191]}
      />
      <mesh
        geometry={nodes.Object_457.geometry}
        material={materials["bread.001"]}
        position={[3.146, 2.548, -2.546]}
      />
      <mesh
        geometry={nodes.Object_459.geometry}
        material={materials["bread.001"]}
        position={[2.864, 2.548, -2.643]}
      />
      <mesh
        geometry={nodes.Object_461.geometry}
        material={materials["bread.001"]}
        position={[3.088, 2.597, -0.581]}
      />
      <mesh
        geometry={nodes.Object_463.geometry}
        material={materials["bread.001"]}
        position={[2.905, 2.548, -0.57]}
      />
      <mesh
        geometry={nodes.Object_465.geometry}
        material={materials.wood_for_glass}
        position={[2.461, 2.496, -3.234]}
      />
      <mesh
        geometry={nodes.Object_467.geometry}
        material={materials.wood_fork}
        position={[3.231, 2.48, -3.275]}
      />
    </group>
  );
};

useGLTF.preload("models/kitchen.glb");
export default Kitchen;
