/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 spiders_portal.glb 
Author: James Rooney Barker (https://sketchfab.com/JamesRooneyBarker)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/the-well-spiders-portal-3eb461d39e8d44b195f4788be530ae79
Title: The Well Spider's Portal
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Spidersportal = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/spiders_portal.glb");
  const { actions } = useAnimations(animations, group);



  useEffect(() => {
    actions["Take 001"].play().setDuration(25);
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.293}
        >
          <group
            name="5335bb001dac4cda8fb75b610bda5192fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="UVd1" position={[108.92, 44.888, -185.549]}>
                  <group name="TilingTextures">
                    <mesh
                      name="TilingTextures_TilingAtlas_Material_0"
                      geometry={
                        nodes.TilingTextures_TilingAtlas_Material_0.geometry
                      }
                      material={materials.TilingAtlas_Material}
                    />
                  </group>
                  <group name="Props" position={[-108.92, -44.888, 185.549]}>
                    <mesh
                      name="Props_SpiderWeb_Material_0"
                      geometry={nodes.Props_SpiderWeb_Material_0.geometry}
                      material={materials.SpiderWeb_Material}
                    />
                    <mesh
                      name="Props_del_0"
                      geometry={nodes.Props_del_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="MovingProps_Rig">
                    <group name="Object_11">
                      <primitive object={nodes._rootJoint} />
                      <group
                        name="Object_13"
                        position={[108.92, 44.888, -185.549]}
                      />
                      <group name="MovingProps" />
                      <skinnedMesh
                        name="Object_14"
                        geometry={nodes.Object_14.geometry}
                        material={materials.material}
                        skeleton={nodes.Object_14.skeleton}
                      />
                    </group>
                  </group>
                  <group
                    name="MovingWeb_Rig"
                    position={[-108.92, -44.888, 185.549]}
                  >
                    <group name="Object_35">
                      <group
                        name="web_ctrl"
                        position={[381.427, 693.969, -167.305]}
                        rotation={[-0.139, 0, 0]}
                      />
                      <primitive object={nodes._rootJoint_1} />
                      <group name="web_moving_01" />
                      <skinnedMesh
                        name="Object_37"
                        geometry={nodes.Object_37.geometry}
                        material={materials.SpiderWeb_Material}
                        skeleton={nodes.Object_37.skeleton}
                      />
                    </group>
                  </group>
                  <group name="Altar" />
                  <group
                    name="PortalObjects"
                    position={[-108.92, -44.888, 185.549]}
                  >
                    <group
                      name="pPlane51"
                      position={[2.756, -11.651, -185.67]}
                      rotation={[-Math.PI, -0.497, -Math.PI]}
                    >
                      <mesh
                        name="pPlane51_PortalCenterGlow_0"
                        geometry={nodes.pPlane51_PortalCenterGlow_0.geometry}
                        material={materials.PortalCenterGlow}
                      />
                    </group>
                    <group
                      name="Portal"
                      position={[-12.788, -41.754, -185.292]}
                      rotation={[-Math.PI, -0.497, -Math.PI]}
                    >
                      <mesh
                        name="Portal_PortalBright_0"
                        geometry={nodes.Portal_PortalBright_0.geometry}
                        material={materials.PortalBright}
                      />
                      <mesh
                        name="Portal_PortalDark_0"
                        geometry={nodes.Portal_PortalDark_0.geometry}
                        material={materials.PortalDark}
                      />
                    </group>
                    <group name="pDisc1" position={[-2.01, 6.901, 13.236]}>
                      <mesh
                        name="pDisc1_Void_0"
                        geometry={nodes.pDisc1_Void_0.geometry}
                        material={materials.Void}
                      />
                    </group>
                    <group
                      name="pPlane68"
                      position={[3.931, -34.625, -18.505]}
                      scale={[0.944, 1.527, 0.927]}
                    >
                      <mesh
                        name="pPlane68_PortalSideGlow_0"
                        geometry={nodes.pPlane68_PortalSideGlow_0.geometry}
                        material={materials.PortalSideGlow}
                      />
                    </group>
                  </group>
                  <group name="Spiderlings" />
                  <group name="MainSpiderRig">
                    <group name="Object_55">
                      <primitive object={nodes._rootJoint_2} />
                      <group
                        name="Object_57"
                        position={[108.92, 44.888, -185.549]}
                      />
                      <group
                        name="IK_Grp"
                        position={[-108.92, -44.888, 185.549]}
                      >
                        <group
                          name="r_leg_01_handle"
                          position={[-229.86, -5.444, 649.632]}
                        />
                        <group
                          name="r_leg_02_handle"
                          position={[-713.365, -0.702, 451.021]}
                        />
                        <group
                          name="l_leg_01_handle"
                          position={[254.979, -2.548, 673.958]}
                        />
                        <group
                          name="l_leg_02_handle"
                          position={[527.891, -4.722, 316.938]}
                        />
                        <group
                          name="r_leg_03_handle"
                          position={[-697.965, -0.036, 7.786]}
                        />
                        <group
                          name="r_leg_04_handle"
                          position={[-629.638, -4.303, -582.892]}
                        />
                        <group
                          name="l_leg_03_handle"
                          position={[680.884, -2.695, -246.542]}
                        />
                        <group
                          name="l_leg_04_handle"
                          position={[445.839, 187.018, -409.91]}
                        />
                      </group>
                      <group name="Spider" />
                      <skinnedMesh
                        name="Object_58"
                        geometry={nodes.Object_58.geometry}
                        material={materials.SpiderMaterial}
                        skeleton={nodes.Object_58.skeleton}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Spidersportal;
useGLTF.preload("models/spiders_portal.glb");
